// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXsBqRBS5d86wq8W5GITk2851Yb-pxZlQ',
    appId: '1:470167890186:web:0645cd127485a7d2a2b2f3',
    messagingSenderId: '470167890186',
    projectId: 'inventory-app-7428b',
    authDomain: 'inventory-app-7428b.firebaseapp.com',
    storageBucket: 'inventory-app-7428b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEKtaaa7XfFkK7JyNxcOAlXT2poJ8CuLw',
    appId: '1:470167890186:android:6ccc7dcfaef75b25a2b2f3',
    messagingSenderId: '470167890186',
    projectId: 'inventory-app-7428b',
    storageBucket: 'inventory-app-7428b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpYekRO-QRDcbfCnAHaJrAb6-5jPvws94',
    appId: '1:470167890186:ios:ce67232556d2e3e8a2b2f3',
    messagingSenderId: '470167890186',
    projectId: 'inventory-app-7428b',
    storageBucket: 'inventory-app-7428b.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpYekRO-QRDcbfCnAHaJrAb6-5jPvws94',
    appId: '1:470167890186:ios:ce67232556d2e3e8a2b2f3',
    messagingSenderId: '470167890186',
    projectId: 'inventory-app-7428b',
    storageBucket: 'inventory-app-7428b.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXsBqRBS5d86wq8W5GITk2851Yb-pxZlQ',
    appId: '1:470167890186:web:1556f655caa10e6aa2b2f3',
    messagingSenderId: '470167890186',
    projectId: 'inventory-app-7428b',
    authDomain: 'inventory-app-7428b.firebaseapp.com',
    storageBucket: 'inventory-app-7428b.firebasestorage.app',
  );

}